package types

import (
	"context"
	"time"
)

// AgentRole identifies which agent produced a StepTrace entry in multi-agent mode.
type AgentRole string

const (
	AgentRolePlanner    AgentRole = "planner"
	AgentRoleCritic     AgentRole = "critic"
	AgentRoleExecutor   AgentRole = "executor"
	AgentRoleVerifier   AgentRole = "verifier"
	AgentRoleResearcher AgentRole = "researcher"
	AgentRoleWriter     AgentRole = "writer"
	AgentRoleSingle     AgentRole = "" // default single-agent mode
)

type Evidence struct {
	Path  string   `json:"path"`
	Lines []string `json:"lines"`
	Query string   `json:"query"`
}

type TokenUsage struct {
	PromptTokens     int `json:"prompt_tokens"`
	CompletionTokens int `json:"completion_tokens"`
	TotalTokens      int `json:"total_tokens"`
}

type StepTrace struct {
	Step        int        `json:"step"`
	Goal        string     `json:"goal"`
	Action      string     `json:"action"`
	Query       string     `json:"query"`
	Observation string     `json:"observation"`
	Evidence    []Evidence `json:"evidence"`
	// Error holds the failure reason when this action failed. It is empty for
	// successful actions. A non-empty Error means the step was recorded as an
	// observation for the planner to react to, rather than aborting the task.
	Error string `json:"error,omitempty"`
	// AgentRole identifies the agent that produced this trace entry.
	// Empty for single-agent (legacy/eino/adk) modes; set in multi-agent mode.
	AgentRole  AgentRole  `json:"agent_role,omitempty"`
	TokenUsage TokenUsage `json:"token_usage,omitempty"`
}

type TaskStatus string

const (
	StatusCreated          TaskStatus = "created"
	StatusRunning          TaskStatus = "running"
	StatusAwaitingApproval TaskStatus = "awaiting_approval"
	StatusPaused           TaskStatus = "paused" // interrupted by graceful shutdown; resumable
	StatusCompleted        TaskStatus = "completed"
	StatusPartial          TaskStatus = "partial"
	StatusFailed           TaskStatus = "failed"
)

func IsTerminalTaskStatus(status TaskStatus) bool {
	return status == StatusCompleted || status == StatusPartial || status == StatusFailed
}

type RiskLevel string

const (
	RiskLevelLow  RiskLevel = "low"
	RiskLevelHigh RiskLevel = "high"
)

type ApprovalRequest struct {
	// ID uniquely identifies this approval request. It is generated by the
	// orchestrator at RegisterApproval time and surfaced to clients via SSE,
	// so the client can disambiguate when more than one approval is pending
	// for the same task (POST /api/tasks/:id/approve {"approval_id": "..."}).
	ID               string         `json:"id"`
	TaskID           string         `json:"task_id"`
	Action           string         `json:"action"`
	RiskLevel        RiskLevel      `json:"risk_level"`
	Workspace        string         `json:"workspace"`
	Parameters       map[string]any `json:"parameters,omitempty"`
	ParameterSummary []string       `json:"parameter_summary,omitempty"`
	Preview          string         `json:"preview,omitempty"`
}

type ApprovalResult struct {
	Approved   bool           `json:"approved"`
	Message    string         `json:"message,omitempty"`
	Parameters map[string]any `json:"parameters,omitempty"`
}

type Task struct {
	ID          string     `json:"id"`
	TenantID    string     `json:"tenant_id"`
	SessionID   string     `json:"session_id,omitempty"`
	SequenceNo  int64      `json:"sequence_no,omitempty"`
	CreatedAt   time.Time  `json:"created_at,omitempty"`
	UpdatedAt   time.Time  `json:"updated_at,omitempty"`
	Goal        string     `json:"goal"`
	Status      TaskStatus `json:"status"`
	MaxSteps    int        `json:"max_steps"`
	StepCount   int        `json:"step_count"`
	Workspace   string     `json:"workspace"`
	Hypothesis  string     `json:"hypothesis"`
	Unresolved  []string   `json:"unresolved"`
	ToolBudget  int        `json:"tool_budget"`
	TokenBudget int        `json:"token_budget"`
	// LLMCallBudget and LLMCostBudgetUSD override process defaults when positive.
	// Accumulated values are persisted so resumed tasks retain their quota state.
	LLMCallBudget       int                `json:"llm_call_budget"`
	LLMCostBudgetUSD    float64            `json:"llm_cost_budget_usd"`
	LLMCalls            int                `json:"llm_calls"`
	LLMEstimatedCostUSD float64            `json:"llm_estimated_cost_usd"`
	Trace               []StepTrace        `json:"trace"`
	FinalAnswer         string             `json:"final_answer"`
	Memories            []Memory           `json:"memories,omitempty"`
	AnswerAudit         *AnswerAuditReport `json:"answer_audit,omitempty"`
}

type TenantLLMUsage struct {
	Calls            int
	EstimatedCostUSD float64
}

type TenantLLMBudget struct {
	MaxCalls            int
	MaxEstimatedCostUSD float64
}

// TenantUsageLedger provides an atomic, cross-task and cross-instance usage
// boundary. PeriodStart is the UTC start of the accounting window.
type TenantUsageLedger interface {
	ReserveTenantLLMCall(ctx context.Context, tenantID string, periodStart time.Time, budget TenantLLMBudget) (TenantLLMUsage, bool, error)
	AddTenantLLMCost(ctx context.Context, tenantID string, periodStart time.Time, estimatedCostUSD float64) error
	GetTenantLLMUsage(ctx context.Context, tenantID string, periodStart time.Time) (TenantLLMUsage, error)
}
