#!/usr/bin/env bash
set -euo pipefail

usage() { echo 'usage: bootstrap.sh --role node-a|node-b|storage|control --assets DIRECTORY [--apply]' >&2; exit 2; }
role= assets= apply=false
while (($#)); do
  case "$1" in
    --role) (($# >= 2)) || usage; role=$2; shift 2 ;;
    --assets) (($# >= 2)) || usage; assets=$2; shift 2 ;;
    --apply) apply=true; shift ;;
    *) usage ;;
  esac
done
case "$role" in node-a|node-b|storage|control) ;; *) usage ;; esac
[[ -n "$assets" ]] || usage
assets=$(cd "$assets" && pwd)
[[ -f "$assets/bootstrap.env" ]] || { echo 'Missing rendered assets' >&2; exit 2; }
# This file is generated by render.py and contains only validated topology.
source "$assets/bootstrap.env"
[[ "$HA_ROLE" == "$role" && "$HA_PREFIX" =~ ^[a-z0-9]+(-[a-z0-9]+)*$ ]] || exit 2
for address in "$HA_NODE_A_IP" "$HA_NODE_B_IP" "$HA_STORAGE_IP" "$HA_CONTROL_IP"; do
  [[ "$address" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit 2
done
echo "Prepare $role for $HA_PREFIX: dedicated packages, service files and shared NFSv4."
[[ "$apply" == true ]] || { echo 'Plan only. Add --apply on the intended fresh test VM.'; exit 0; }
[[ $(uname -s) == Linux && $(id -u) == 0 ]] || { echo 'Apply requires Linux root' >&2; exit 2; }
[[ $(cat /proc/1/comm) == systemd ]] || { echo 'systemd must be PID 1' >&2; exit 2; }
case "$role" in
  node-a) expected_ip=$HA_NODE_A_IP ;; node-b) expected_ip=$HA_NODE_B_IP ;;
  storage) expected_ip=$HA_STORAGE_IP ;; control) expected_ip=$HA_CONTROL_IP ;;
esac
ip -4 -o addr show | awk '{split($4,a,"/"); print a[1]}' | grep -Fxq "$expected_ip" || {
  echo 'Topology does not match this guest address' >&2; exit 2;
}
root=/etc/ai-agent-ha
[[ ! -e "$root" && ! -L "$root" ]] || { echo 'Existing bootstrap state; review it manually instead of overwriting' >&2; exit 2; }
[[ ! -e /etc/ai-agent/ai-agent.env && ! -e /opt/ai-agent/workspace ]] || { echo 'Use a fresh test VM' >&2; exit 2; }
umask 077
install -d -m 0700 "$root"
install -m 0600 "$assets/bootstrap.env" "$root/bootstrap.env"
printf '%s\n' "$HA_PREFIX:$role" > "$root/identity"
# A failure leaves the marker and partial state for inspection; no automatic deletion.
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq nfs-common curl python3 jq ca-certificates
command -v docker >/dev/null || { echo 'Docker is missing from the selected Ubuntu image' >&2; exit 2; }
docker compose version >/dev/null
kit=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
install -d -m 0755 /opt/ai-agent-ha/bin
install -m 0644 "$kit/workspace-probe.py" /opt/ai-agent-ha/bin/workspace-probe.py
if getent group ai-agent >/dev/null; then
  [[ $(getent group ai-agent | cut -d: -f3) == 21088 ]] || exit 2
else
  groupadd --gid 21088 ai-agent
fi
if id ai-agent >/dev/null 2>&1; then
  [[ $(id -u ai-agent) == 21088 && $(id -g ai-agent) == 21088 ]] || exit 2
else
  useradd --uid 21088 --gid ai-agent --system --no-create-home --shell /usr/sbin/nologin ai-agent
fi

if [[ "$role" == storage ]]; then
  apt-get install -y -qq nfs-kernel-server
  install -d -o ai-agent -g ai-agent -m 0750 /srv/ai-agent-ha/workspace /srv/ai-agent-ha/workspace/ha-fixture
  printf '%s\n' 'Isolated AI Agent HA test fixture. The shared README is read-only test input.' > /srv/ai-agent-ha/workspace/ha-fixture/README.md
  chown ai-agent:ai-agent /srv/ai-agent-ha/workspace/ha-fixture/README.md
  chmod 0440 /srv/ai-agent-ha/workspace/ha-fixture/README.md
  install -m 0644 "$assets/exports" /etc/exports.d/ai-agent-ha.exports
  exportfs -ra
  systemctl enable --now nfs-server
  install -m 0600 "$assets/storage.env" "$root/storage.env"
  install -m 0600 "$assets/compose.yaml" "$root/compose.yaml"
  # Docker's redis user needs file read access; parent directory stays root-only.
  install -m 0644 "$assets/redis.conf" "$root/redis.conf"
  docker compose --env-file "$root/storage.env" -f "$root/compose.yaml" config --quiet
  docker compose --env-file "$root/storage.env" -f "$root/compose.yaml" up -d --wait
else
  install -d -m 0755 /opt/ai-agent
  install -d -o ai-agent -g ai-agent -m 0750 /opt/ai-agent/workspace
  mount_unit=$(systemd-escape --path --suffix=mount /opt/ai-agent/workspace)
  [[ ! -e "/etc/systemd/system/$mount_unit" ]] || exit 2
  cat > "/etc/systemd/system/$mount_unit" <<EOF
[Unit]
Description=Dedicated HA NFSv4 workspace
Wants=network-online.target
After=network-online.target
[Mount]
What=$HA_STORAGE_IP:/
Where=/opt/ai-agent/workspace
Type=nfs
Options=vers=4.2,proto=tcp,hard,timeo=600,retrans=2
[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
  systemctl enable --now "$mount_unit"
  findmnt -n -t nfs,nfs4 --target /opt/ai-agent/workspace >/dev/null
  runuser -u ai-agent -- test -r /opt/ai-agent/workspace/ha-fixture/README.md
  if [[ "$role" == node-* ]]; then
    install -d -o root -g ai-agent -m 0750 /etc/ai-agent /opt/ai-agent-ha/runtime
    install -m 0600 "$assets/ai-agent.env" /etc/ai-agent/ai-agent.env
    install -o root -g ai-agent -m 0640 "$assets/ha-config.json" /etc/ai-agent/ha-config.json
    install -o root -g ai-agent -m 0640 "$assets/teams.yaml" /opt/ai-agent-ha/runtime/teams.yaml
    ln -s /opt/ai-agent/skills /opt/ai-agent-ha/runtime/skills
    install -d -m 0755 /etc/systemd/system/ai-agent.service.d
    cat > /etc/systemd/system/ai-agent.service.d/ha-fixture.conf <<'EOF'
[Unit]
RequiresMountsFor=/opt/ai-agent/workspace
[Service]
WorkingDirectory=/opt/ai-agent-ha/runtime
EOF
  else
    apt-get install -y -qq build-essential git
    install -m 0755 "$kit/control-worker.sh" /opt/ai-agent-ha/bin/control-worker.sh
    install -m 0644 "$kit/verify-contracts.py" /opt/ai-agent-ha/bin/verify-contracts.py
    install -m 0600 "$assets/control.env" "$root/control.env"
    install -m 0600 "$assets/stub.env" "$root/stub.env"
    install -d -o root -g ai-agent -m 0750 /opt/ai-agent-ha/stub
    install -o root -g ai-agent -m 0640 "$assets/offline_stub.py" /opt/ai-agent-ha/stub/offline_stub.py
    install -m 0600 "$assets/compose.yaml" "$root/compose.yaml"
    install -m 0644 "$assets/prometheus.json" "$root/prometheus.json"
    install -m 0644 "$assets/metrics.key" "$root/metrics.key"
    cat > /etc/systemd/system/ai-agent-ha-stub.service <<'EOF'
[Unit]
Description=Offline HA transport fixture
After=network-online.target
[Service]
User=ai-agent
Group=ai-agent
EnvironmentFile=/etc/ai-agent-ha/stub.env
ExecStart=/usr/bin/python3 /opt/ai-agent-ha/stub/offline_stub.py
Restart=on-failure
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
PrivateTmp=true
[Install]
WantedBy=multi-user.target
EOF
    systemctl daemon-reload
    systemctl enable --now ai-agent-ha-stub.service
    docker compose -f "$root/compose.yaml" config --quiet
    docker compose -f "$root/compose.yaml" run --rm --no-deps --entrypoint promtool prometheus check config /etc/prometheus/prometheus.yml
    docker compose -f "$root/compose.yaml" up -d --wait
  fi
fi
printf '%s\n' 'bootstrap-complete-not-accepted' > "$root/status"
echo 'Bootstrap complete. Verify shared read/write, storage credentials and monitoring before deployment.'
